steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/dbt-cloud-run", "."]
  
  # Step 2: Push the image to Google Container Registry (GCR) or Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/dbt-cloud-run"]
  
  # Step 3: Deploy the container image to Cloud Run Jobs
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: 
      - "run"
      - "jobs"
      - "deploy"
      - "dbt-cloud-run"
      - "--image=gcr.io/$PROJECT_ID/dbt-cloud-run"
      - "--region=us-central1"
      - "--memory=2Gi"
      - "--max-retries=4"
      - "--task-timeout=3600" # optional: 1 hour timeout

# Define the images used in the build process
images:
  - "gcr.io/$PROJECT_ID/dbt-cloud-run"
